version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/node/
permissions:
  - object: /home/ubuntu
    owner: ubuntu
    group: ubuntu
    type:
      - directory
      - file
hooks:
  BeforeInstall:
    - location: deployScripts/AB_Scripts/install1.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: deployScripts/AB_Scripts/post_install1.sh
      timeout: 600
      runas: root
  ApplicationStart:
    - location: deployScripts/AB_Scripts/run1.sh
      timeout: 120
      runas: root
  # ApplicationStop:
  #   - location: deployScripts/AB_Scripts/stop.sh
  #     timeout: 120
  #     runas: root
  ValidateService:
    - location: deployScripts/AB_Scripts/validate.sh
      timeout: 60
      runas: root
